"""Core functionality for the Provium platform."""

from importlib.metadata import version

from .artifact import (
    Artifact,
    ArtifactCatalog,
    ArtifactDefinition,
    ArtifactHeader,
    ArtifactReadBinding,
    ArtifactReader,
    ArtifactWriteBinding,
    ArtifactWriter,
    BodyRegion,
    StagedArtifact,
    decode_header,
    discover_artifact_catalogs,
    encode_header,
    reset_artifact_discovery,
    stage_artifact,
)
from .procedure import (
    ConfigurationSnapshot,
    JsonValue,
    PreparedProcedure,
    Procedure,
    ProcedureCatalog,
    ProcedureConfig,
    ProcedureConfigurationError,
    ProcedureContract,
    ProcedureContractMetadata,
    ProcedureDefinition,
    ProcedureExecutor,
    ProcedureInputField,
    ProcedureInputs,
    ProcedureIOField,
    ProcedureIOFieldMetadata,
    ProcedureOptionalInputField,
    ProcedureOptionalOutputField,
    ProcedureOutputField,
    ProcedureOutputs,
    ProcedureProcessContext,
    ProcedureRepeatedInputField,
    ProcedureSetupContext,
    compose_configuration,
    discover_procedure_catalogs,
    input,
    load_json_configuration,
    load_yaml_configuration,
    optional_input,
    optional_output,
    output,
    repeated_input,
    reset_procedure_discovery,
    validate_procedure_configuration,
)
from .provenance import (
    ArtifactLineage,
    ArtifactRecord,
    ArtifactReference,
    ProcedureExecutionRecord,
    ProcedureRecord,
)
from .session import Session, current_session, session

__version__ = version("provium")

__all__ = [
    "Artifact",
    "ArtifactCatalog",
    "ArtifactDefinition",
    "ArtifactHeader",
    "ArtifactLineage",
    "ArtifactReadBinding",
    "ArtifactReader",
    "ArtifactRecord",
    "ArtifactReference",
    "ArtifactWriter",
    "BodyRegion",
    "StagedArtifact",
    "ArtifactWriteBinding",
    "ConfigurationSnapshot",
    "JsonValue",
    "PreparedProcedure",
    "Procedure",
    "ProcedureCatalog",
    "ProcedureConfig",
    "ProcedureConfigurationError",
    "ProcedureContract",
    "ProcedureContractMetadata",
    "ProcedureDefinition",
    "ProcedureExecutionRecord",
    "ProcedureExecutor",
    "ProcedureIOField",
    "ProcedureIOFieldMetadata",
    "ProcedureInputField",
    "ProcedureInputs",
    "ProcedureOptionalInputField",
    "ProcedureOptionalOutputField",
    "ProcedureOutputField",
    "ProcedureOutputs",
    "ProcedureProcessContext",
    "ProcedureRepeatedInputField",
    "ProcedureRecord",
    "ProcedureSetupContext",
    "Session",
    "__version__",
    "compose_configuration",
    "current_session",
    "decode_header",
    "discover_artifact_catalogs",
    "discover_procedure_catalogs",
    "encode_header",
    "input",
    "load_json_configuration",
    "load_yaml_configuration",
    "optional_input",
    "optional_output",
    "output",
    "repeated_input",
    "reset_artifact_discovery",
    "reset_procedure_discovery",
    "session",
    "stage_artifact",
    "validate_procedure_configuration",
]
